name: Update Personal Stats

on:
    schedule:
        # Run at 00:00 UTC every day
        - cron: "0 0 * * *"
    # Allow you to click a button to run it manually
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build-stats:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Run Stats Script
              env:
                  STATS_TOKEN: ${{ secrets.STATS_TOKEN }}
                  GITHUB_REPOSITORY: ${{ github.repository }}
              run: node scripts/generate.js

            - name: Commit and Push Changes
              run: |
                  git config --global user.name "Stats Bot"
                  git config --global user.email "bot@noreply.github.com"
                  git add generated/*.svg
                  # Only commit if the files actually changed
                  git commit -m "Update stats [skip ci]" || exit 0
                  git push
